- name: Deploy regapp application to Kubernetes (EKS)
  hosts: kubernetes
  become: yes
  become_method: sudo

  vars:
    ansible_python_interpreter: /usr/bin/python3
    app_name: regapp
    app_tag: "{{ app_tag | default('latest') }}"
    aws_account_id: "732583169994"
    aws_region: "us-east-1"
    kubeconfig_path: /home/ansadmin/.kube/config
    app_deployment_yaml: /var/lib/jenkins/workspace/newdeployment/webapp-deployment.yaml
    app_service_yaml: /var/lib/jenkins/workspace/newdeployment/webapp-service.yaml
    full_image_path: "732583169994.dkr.ecr.us-east-1.amazonaws.com/regapp"

  tasks:
    - name: Ensure Deployment YAML exists
      ansible.builtin.stat:
        path: "{{ app_deployment_yaml }}"
      register: deployment_file

    - name: Ensure Service YAML exists
      ansible.builtin.stat:
        path: "{{ app_service_yaml }}"
      register: service_file

    - name: Update Deployment image with new tag
      ansible.builtin.replace:
        path: "{{ app_deployment_yaml }}"
        regexp: '(image:\s*732583169994\.dkr\.ecr\.us-east-1\.amazonaws\.com/regapp:)([^\\s]+)'
        replace: 'image: {{ full_image_path }}:{{ app_tag }}'
      when: deployment_file.stat.exists

    - name: Apply Deployment YAML to Kubernetes
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        src: "{{ app_deployment_yaml }}"
      when: deployment_file.stat.exists

    - name: Apply Service YAML to Kubernetes
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        src: "{{ app_service_yaml }}"
      when: service_file.stat.exists

    - name: Debug which image tag is being used
      debug:
        msg: "🚀 Deploying regapp image: {{ full_image_path }}:{{ app_tag }}"
